### ISSUE TITLE
Vuetify Loader error

### ISSUE THREAD

**Issue by BaileyJM02** [jexia/DataViewer#2]
After cloning into a new folder, installing npm modules and running `npm run serve` the error below is shown:
```
ERROR  Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (.../DataViewer/node_modules/vuetify-loader/lib/plugin.js:18:13)
    at webpack (.../DataViewer/node_modules/webpack/lib/webpack.js:51:13)
    at serve (.../DataViewer/node_modules/@vue/cli-service/lib/commands/serve.js:162:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dataview@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
```

**Comment by MishaJexia** [comment]
Thank you Bailey for fixing this!
